fix warnings. use '\'' instead of '''
```
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_192).
Type in expressions for evaluation. Or try :help.

scala> '''
<console>:12: warning: deprecated syntax for character literal (use '\'' for single quote)
       '''
       ^
res0: Char = '
```

```
Welcome to Scala 2.13.0-M5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_192).
Type in expressions for evaluation. Or try :help.

scala> '''
       ^
       error: empty character literal (use '\'' for single quote)
         ^
       error: unclosed character literal (or use " not ' for string literal)
```